import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import '@radix-ui/themes/styles.css'; 

const inter = Inter({ subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className = {inter.className}>
          <Header/>
          {children}
          <footer className="container py-16 text-gray-500 px-16">
            Job Board &copy; 2024 - All rights reserved.
          </footer>
      </body>
    </html>
  );
}
